# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9fddb7f5184b8662eaa22d7f9347212d4f129f542eb070e7b4311f903a679ead87609e9d895f4290c714e23f24b83d56835ec9fb49bce5a08d0700819fccaa71

test:
  secret_key_base: a63386f4e142a5d6b9f2d760140f4d1402fb4f77342db1bbfa85f49d82d0f888e78785f786e28b7a3e774b48e2e471c32ebe1a789e1db51366cad32a8377b96c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
